#!/bin/bash
sudo systemctl enable systemd-resolved
sudo systemctl start systemd-resolved
sudo systemctl restart NetworkManager 
sudo systemctl restart dhcpcd
sudo dhcpcd 
sudo echo 'nameserver 8.8.8.8' > /etc/resolv.conf
sudo echo 'nameserver 8.8.4.4' >> /etc/resolv.conf
sudo pacman-mirrors --fasttrack 
sudo pacman -Syy
